php/symfony/my_app/src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnimalRepository::class)]
class Animal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $Description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Image;

    #[ORM\Column(type: 'integer')]
    private $Poids;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getPoids(): ?string
    {
        return $this->Poids;
    }

    public function setPoids(string $Poids): self
    {
        $this->Poids = $Poids;

        return $this;
    }
}

php/symfony/my_app/src/Form/AnimalType.php
<?php

namespace App\Form;

use App\Entity\Animal;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnimalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Description')
            ->add('Image')
            ->add('Poids')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Animal::class,
        ]);
    }
}

php/symfony/my_app/src/Form/EspeceType.php
<?php

namespace App\Form;

use App\Entity\Espece;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EspeceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Espece::class,
        ]);
    }
}

php/symfony/my_app/src/Controller/AnimalController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Repository\AnimalRepository;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Form\AnimalType;
use Doctrine\ORM\EntityManagerInterface;

class AnimalController extends AbstractController
{
    #[Route('/', name: 'amimaux')]


    public function index(AnimalRepository $repository)
    {
        $animaux = $repository->findAll();
        return $this->render('animal/index.html.twig', [
            "animaux" => $animaux,
        ]);
    }

    #[Route('/animal/{id}', name: 'unAnimal')]


    public function afficheAnimal($id, AnimalRepository $repository)
    {
        $animaux = $repository->find($id);
        return $this->render('animal/affani.html.twig', [
            "animal" => $animaux,
        ]);
    }

    #[Route('/poids/{poids}', name: 'triPoids')]


    public function triPoids(AnimalRepository $rep, $poids): Response
    {
        $animaux = $rep->findByPoidsUnder($poids);
        return $this->render('animal/index.html.twig', [
            "animaux" => $animaux,
        ]);
    }

    #[Route('/animalcreation', name:'creation')]
    #[Route('/modif/{id}', name: 'modif')]

    public function modifAnimal(Animal $animal=null,Request $request, EntityManagerInterface $om)
    {
        if (!$animal) {
            $animal = new Animal();
        }
        $form = $this->createForm(AnimalType::class,$animal);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $om->persist($animal);
            $om->flush();
            $this->addFlash('success', "L'action a été effectué");
            return $this->redirectToRoute("amimaux");
        }

        return $this->render('animal/modifani.html.twig',[
            "animal" => $animal,
            "form" => $form->createView()
        ]);

    }
}

php/symfony/my_app/src/Controller/EspeceController.php
<?php

namespace App\Controller;

use App\Entity\Espece;
use App\Repository\EspeceRepository;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Form\EspeceType;
use Doctrine\ORM\EntityManagerInterface;

class AnimalController extends AbstractController
{
    #[Route('/', name: 'amimaux')]


    public function index(EspeceRepository $repository)
    {
        $especes = $repository->findAll();
        return $this->render('espece/index.html.twig', [
            "espece" => $especes,
        ]);
    }

    #[Route('/espece/{id}', name: 'uneEspece')]


    public function afficheEspece($id, EspeceRepository $repository)
    {
        $especes = $repository->find($id);
        return $this->render('espece/affesp.html.twig', [
            "espece" => $especes,
        ]);
    }

    #[Route('/poids/{poids}', name: 'triPoids')]


    public function triPoids(EspeceRepository $rep, $poids): Response
    {
        $especes = $rep->findByPoidsUnder($poids);
        return $this->render('espece/index.html.twig', [
            "espece" => $especes,
        ]);
    }

    #[Route('/espececreation', name:'creation')]
    #[Route('/modif/{id}', name: 'modif')]

    public function modifEspece(Espece $espece=null,Request $request, EntityManagerInterface $om)
    {
        if (!$espece) {
            $espece = new Espece();
        }
        $form = $this->createForm(EspeceType::class,$espece);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $om->persist($espece);
            $om->flush();
            $this->addFlash('success', "L'action a été effectué");
            return $this->redirectToRoute("amimaux");
        }

        return $this->render('espece/modifesp.html.twig',[
            "espece" => $espece,
            "form" => $form->createView()
        ]);

    }
}

php/symfony/my_app/templates/animal/affani.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil{% endblock %}
{% block monTitre %}Voici la liste{% endblock %}

{% block body %}
        
        <div class="col-auto">
            <h2>{{animal.nom}}</h2>
            <div>{{animal.description}}</div>
            <div>{{animal.poids}}</div>
        </div>
        <div class="col-2 text-center">
            <img src="../images/{{animal.image}}">
        </div>
    </div>

{% endblock %}

php/symfony/my_app/templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil{% endblock %}
{% block monTitre %}Voici la liste{% endblock %}

{% block body %}

<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    img {max-width: 200px; max-height : 200px; border-radius:100px; }

</style>

    {% for animal in animaux %}
        <div class="row align-items-center">
        
        <div class="col-auto">
            <h2>{{animal.nom}}</h2>
            <div>{{animal.description}}</div>
            <div>{{animal.poids}}</div>
        </div>
        <div class="col-2 text-center">
            <img src="images/{{animal.image}}">
        </div>
    </div>

    {% endfor %}
{% endblock %}

php/symfony/my_app/templates/animal/modifani.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification animal{% endblock %}

{% block body %}

    {{form_start(form)}}
        {{form_widget(form)}}
        <input type="submit">
    {{form_end(form)}}     
 
{% endblock %}

php/symfony/my_app/templates/espece/affesp.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil{% endblock %}
{% block monTitre %}Voici la liste{% endblock %}

{% block body %}
        
        <div class="col-auto">
            <h2>{{espece.nom}}</h2>
            <div>{{espece.description}}</div>
        </div>

{% endblock %}

php/symfony/my_app/templates/espece/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil{% endblock %}
{% block monTitre %}Voici la liste{% endblock %}

{% block body %}

<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    img {max-width: 200px; max-height : 200px; border-radius:100px; }

</style>

    {% for espece in especes %}
        <div class="row align-items-center">
        
            <div class="col-auto">
                <h2>{{espece.nom}}</h2>
                <div>{{espece.description}}</div>
            </div>
            
        </div>

    {% endfor %}
{% endblock %}

php/symfony/my_app/templates/espece/modifesp.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une espèce{% endblock %}

{% block body %}

    {{form_start(form)}}
        {{form_widget(form)}}
        <input type="submit">
    {{form_end(form)}}     
 
{% endblock %}